# Generated by Django 2.2.3 on 2019-08-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190702_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='pub_date'),
        ),
    ]
